### ISSUE TITLE
Plot module not found

### ISSUE THREAD

**Issue by sinaebrahimi** [moooontoo/Latency-Equalization-E2E-NS-RL#2]
Hi,

Thank you very much for sharing the code of your paper.
I wanted to start by running DTDP.py, but I got the very first error. There is no file named Plot.py in the folders, and also I tried installing this package (it is surely irrelevant: https://github.com/yuhangwang/plot). 

I am trying to run the code in colab. Is there any tricks to prevent this error?

ModuleNotFoundError                       Traceback (most recent call last)
[/content/Latency-Equalization-E2E-NS-RL-main/code/DTDP.py](https://localhost:8080/#) in <module>
      9 np.random.seed(0)
     10 #from Test import test
---> 11 from Plot import plot
     12 lowerbound = 0.1
     13 upperbound = 0.9

ModuleNotFoundError: No module named 'Plot'

**Comment by sinaebrahimi** [comment]
Hi, 

Is there any file regarding this?

**Comment by moooontoo** [comment]
The 'Plot' module is not important and it can be disabled by annotating related lines. Maybe you can try the updated code to solve this problem (No such file or directory: '../data/data_500/maprecord.txt').

**Comment by moooontoo** [comment]
Besides, the number of waiting-embedded SFCs should be equal to the number of users. You also need to develop the structure of the SFCs, like the readme.

**Comment by sinaebrahimi** [comment]
> The 'Plot' module is not important and it can be disabled by annotating related lines. Maybe you can try the updated code to solve this problem (No such file or directory: '../data/data_500/maprecord.txt').

Thank you for your reply, @moooontoo.
I had commented this line before ('from Plot import plot') an that error was resolved.

Thanks for updating the code. This problem (No such file or directory: '../data/data_500/maprecord.txt') is now resolved.
However, I had another problem with other files when running DTDP.py.

Sorry if I am such a beginner in this. I will paste the entire error here:

runfile('/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code/DTDP.py', wdir='/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code')
***********第1次**********************第1次**********************第1次***********
Network configs...
{'BW_sc': 180000.0,
 'N0': 5e-22,
 'c_num': 20,
 'latency_limit': 10,
 'latency_limit2': 200,
 'loss_fac': 1,
 'mbs_number': 1,
 'net_size': (100, 100),
 'rate_limit': 300000.0,
 'reward_alpha': 1,
 'sbs_number': 1,
 'sep': 5,
 'sp_max': 1,
 'u_number': 20}

[>^<]There have data
Traceback (most recent call last):

  File "/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code/replay_memory.py", line 117, in load
    tim.append(int(datas[i].split('_')[0]))

ValueError: invalid literal for int() with base 10: 'memory'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-66dfab90a6fa>", line 1, in <module>
    runfile('/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code/DTDP.py', wdir='/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code/DTDP.py", line 42, in <module>
    l1, r,ssl =rlRan(sla, target_net, act_net, train)   #0.001的学习率，300个episode得到一个接近最终的结果

  File "/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code/ran.py", line 124, in rlRan
    memory = ReplayMemory(AgentConfig)

  File "/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code/replay_memory.py", line 20, in __init__
    self.actions, self.screens, self.rewards, self.count, self.current = self.load()

  File "/home/sina/Dropbox/Sina/tnsm22bai (DRL- E2E Latency Equalization)/Latency-Equalization-E2E-NS-RL-main/code/replay_memory.py", line 131, in load
    datas.close()

AttributeError: 'list' object has no attribute 'close'

**Comment by sinaebrahimi** [comment]
> Besides, the number of waiting-embedded SFCs should be equal to the number of users. You also need to develop the structure of the SFCs, like the readme.

I cannot understand why the number of waiting-embedded SFCs should be equal to the number of users. Also, it was not very clear with the readme. It would be very helpful if you added some more instructions to that. 

Thank you very much in advance.

**Comment by moooontoo** [comment]
> 

In this paper, I specify that since different service function chains（SFCs） must handle the traffic from different users, the total number of users must coincide with the total number of SFCs.

**Comment by sinaebrahimi** [comment]
Sorry, I can't totally understand the 'coincide' you mean. Can you elaborate with an example?

**Comment by zarah93** [comment]
@moooontoo Could you please let me know  what the steps to create the structure. I have an issue in ran.py, and two issues in replay_memory.py

**Comment by XMstudying** [comment]
运行DSDP和DTDP和static文件都是一个错误，具体就是replay_memory中load函数for i in range(len(datas)): 
tim.append(int(datas[i].split('_')[0]))中，datas中的文件没有带有_和数字的文件名，只有一个memory文件，tim总是0，请问如何提取数据啊，是不是博主忘记放入一些文件，求解决谢谢博主
